# home machine scripts

cinst 1password 
cinst 7zip 
cinst autohotkey.portable 
cinst autoit.commandline 
cinst beyondcompare 
cinst codecov
cinst chocolatey
cinst chocolatey-core.extension
cinst docker
cinst dropbox
cinst FiraCode
cinst git
cinst git.install
cinst git-fork
cinst Gow
cinst golang
cinst ilspy 
cinst insomnia-rest-api-client
cinst launchy 
cinst lockhunter 
cinst nvm
cinst NuGet.CommandLine
cinst paint.net
cinst psake
cinst redis-64
cinst spotify 
cinst SQLite
cinst sqlite.shell
cinst sublimetext3
cinst vlc
cinst oh-my-posh