# home machine scripts

cinst 1password 
cinst 7zip 
cinst beyondcompare 
cinst codecov
cinst chocolatey
cinst chocolatey-core.extension
cinst docker-desktop
cinst FiraCode
cinst git
cinst git.install
cinst git-fork
cinst golang
cinst ilspy 
cinst insomnia-rest-api-client
cinst lockhunter 
cinst nvm
cinst NuGet.CommandLine
cinst paint.net
cinst spotify 
cinst SQLite
cinst sqlite.shell
cinst sublimetext3
cinst vlc
cinst oh-my-posh
cinst microsoft-windows-terminal
cinst powertoys
cinst vscode
cinst firefox
cinst python
