# work machine scripts

cinst 7zip 
cinst 7zip.install 
cinst adexplorer 
cinst asmspy 
cinst autohotkey.portable 
cinst conemu
cinst chocolatey 
cinst chocolatey-core.extension 
cinst chocolatey-windowsupdate.extension 
cinst clipx
cinst docker 
cinst DotNet4.5.1 
cinst DotNet4.6.1 
cinst dotnet4.7.1 
cinst dotnetcore 
cinst dotnetcore-runtime 
cinst dotnetcore-runtime.install 
cinst Filezilla
cinst Firefox 
cinst FiraCode
cinst forticlientvpn
cinst gpg4win
cinst git 
cinst gitextensions 
cinst git-fork 
cinst Gow 
cinst golang
cinst ilspy 
cinst insomnia-rest-api-client 
cinst keepass.install 
cinst launchy 
cinst libjpeg-turbo 
cinst linqpad5 
cinst linqpad5.install 
cinst lockhunter 
cinst mkcert
cinst mm-choco.extension 
cinst nodejs 
cinst nodejs.install 
cinst notepadplusplus
cinst nuget.commandline 
cinst OptiPNG 
cinst ozcode
cinst paint.net 
cinst PhantomJS 
cinst powershell
cinst prefix
cinst python 
cinst python3 
cinst qttabbar 
cinst rdcman 
cinst redis-64
cinst ruby 
cinst rust
cinst soapui
cinst SQLite 
cinst sublimetext3
cinst vscode