# work machine scripts

cinst 7zip
cinst 7zip.install
cinst autohotkey.portable
cinst autorest
cinst clipx
cinst ConEmu
cinst DotNet4.0
cinst DotNet4.5.1
cinst fiddler
cinst filezilla
cinst gimp
cinst git
cinst gitextensions
cinst Gow
cinst ilspy
cinst keepass.install
cinst launchy
cinst libjpeg-turbo
cinst linqpad5
cinst linqpad5.install
cinst lockhunter
cinst mm-choco.extension
cinst nodejs.install
cinst notepadplusplus
cinst NuGet.CommandLine
cinst OptiPNG
cinst paint.net
cinst PhantomJS
cinst python
cinst python3
cinst qttabbar
cinst rktools.2003
cinst ruby
cinst skype
cinst SourceTree